"""fix relationships (primaryhoin) in  users table

Revision ID: 669bc4bd7d56
Revises: 3861bae38e3a
Create Date: 2023-10-05 20:16:20.748834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '669bc4bd7d56'
down_revision: Union[str, None] = '3861bae38e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
