"""add tweets table and update media table

Revision ID: 1f5ebc96dab9
Revises: 90fa05359b83
Create Date: 2023-10-11 20:09:38.962150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5ebc96dab9'
down_revision: Union[str, None] = '90fa05359b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('create_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('media', sa.Column('tweet_id', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('user_id', sa.Integer()))
    op.create_foreign_key(None, 'media', 'tweets', ['tweet_id'], ['id'])
    op.create_foreign_key(None, 'media', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'tweet_id')
    op.drop_table('tweets')
    # ### end Alembic commands ###
