{
 "title": "FastAPI dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total API Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (http_requests_total{status=\"2xx\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(status) (http_requests_total{status=\"3xx\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(status) (http_requests_total{status=\"4xx\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(status) (http_requests_total{status=\"5xx\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Upload/Download",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (http_request_size_bytes_sum{instance=\"server_app:5000\"})",
     "legendFormat": "Auto"
    },
    {
     "expr": "sum by(instance) (http_response_size_bytes_sum{instance=\"server_app:5000\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload/Download per min",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (delta(http_request_size_bytes_sum{instance=\"server_app:5000\"}[1m]))",
     "legendFormat": "Auto"
    },
    {
     "expr": "sum by(instance) (delta(http_response_size_bytes_sum{instance=\"server_app:5000\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(instance) (delta(http_requests_total{instance=\"server_app:5000\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total 2xx Successful responses ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (http_requests_total{status=\"2xx\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total 3xx Successful responses ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (http_requests_total{status=\"3xx\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total 4xx Successful responses ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (http_requests_total{status=\"4xx\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total 5xx Successful responses ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (http_requests_total{status=\"5xx\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2xx requests per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(status) (delta(http_requests_total{status=\"2xx\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3xx requests per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "sum by(status) (delta(http_requests_total{status=\"3xx\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx requests per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(status) (delta(http_requests_total{status=\"4xx\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx requests per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "sum by(status) (delta(http_requests_total{status=\"5xx\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}